baseURL = "https://kevinmasson.fr"
languageCode = "en-us"
title = "Kevin Masson - Photographe de Paysage"
theme = "v1"
disableKinds = ["taxonomyTerm", "taxonomy", "section"]

[taxonomies]
    category = "categories"
    tag = "tags"

[params]
  author = "Kevin Masson"
  description = "Photographe amateur basé à Strasbourg."

[markup.goldmark.renderer]
unsafe= true
